table Calendario
	lineageTag: 5ae2e9f7-e633-4797-b978-e5250939504f

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 35f6de76-5675-43b4-aa98-73065fc7ef9a
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: ca33c6b3-b597-449e-b897-7f07dbd4c3df
			defaultHierarchy: LocalDateTable_fa9eeac4-ca44-4d61-b7ff-012545b1877d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 75493f26-f435-4b52-afad-8fcad5255dba
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: 38bd72a8-3466-484f-b3b8-52cca7fc9e04
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Nome_Mes
		dataType: string
		lineageTag: 442c0e44-c7c8-4cd2-933d-edc474149a14
		summarizeBy: none
		sourceColumn: Nome_Mes
		sortByColumn: Mes

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Dia_Mes
		dataType: int64
		formatString: 0
		lineageTag: 8399a57e-4762-4984-889f-69f63c1bf586
		summarizeBy: sum
		sourceColumn: Dia_Mes

		annotation SummarizationSetBy = Automatic

	column Dia_Ano
		dataType: int64
		formatString: 0
		lineageTag: 22f8907e-3cf7-44d5-bad0-d27f258efbb8
		summarizeBy: sum
		sourceColumn: Dia_Ano

		annotation SummarizationSetBy = Automatic

	column Dia_Semana
		dataType: int64
		formatString: 0
		lineageTag: 8281ff5b-f353-4679-bcea-8eaff3fd8c84
		summarizeBy: sum
		sourceColumn: Dia_Semana

		annotation SummarizationSetBy = Automatic

	column Nome_Dia_Semana
		dataType: string
		lineageTag: 52d154a2-79f3-4013-93d6-45545e9f2c9b
		summarizeBy: none
		sourceColumn: Nome_Dia_Semana

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: 991a7d33-3b5f-4fac-bd7f-e8eae974a393
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Semana_Ano
		dataType: int64
		formatString: 0
		lineageTag: 52522f8d-a94c-4a65-ab41-798abe261c00
		summarizeBy: sum
		sourceColumn: Semana_Ano

		annotation SummarizationSetBy = Automatic

	column Semana_Mes
		dataType: int64
		formatString: 0
		lineageTag: bd5cf3ca-cea4-42a9-a51a-ac9d28ed009b
		summarizeBy: sum
		sourceColumn: Semana_Mes

		annotation SummarizationSetBy = Automatic

	column 'Primeiros caracteres'
		dataType: string
		lineageTag: 883deec7-a5da-40e8-99ac-6a1b68ecd80b
		summarizeBy: none
		sourceColumn: Primeiros caracteres

		annotation SummarizationSetBy = Automatic

	column 'Primeiros caracteres.1'
		dataType: string
		lineageTag: 22c5ac8e-2400-4ef2-8546-221f595a7bd7
		summarizeBy: none
		sourceColumn: Primeiros caracteres.1

		annotation SummarizationSetBy = Automatic

	partition Calendario = m
		mode: import
		source = ```
				let
				    AnoInicial = 2010,
				    AnoFinal = 2025,
				    //Declara uma data inicial
				    DataInicial = Date.StartOfYear(#date(AnoInicial, 1, 1)),
				    //Declara uma data final
				    DataFinal = Date.EndOfYear(#date(AnoFinal, 12, 31)),
				    //Conta a quantidade de dias entre as duas datas
				    QtdeDias = Duration.Days(DataFinal-DataInicial)+1,
				    //Cria lista de datas
				    Datalist = List.Dates(DataInicial,QtdeDias,#duration(1,0,0,0)),
				    //Converter para Tabela
				    ConvertTabela = Table.FromList(Datalist, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    //Altera Tipo
				    AlteraTipo = Table.TransformColumnTypes(ConvertTabela,{{"Column1", type date}}),
				    //Renomeia Coluna
				    RenomeiaColuna = Table.RenameColumns(AlteraTipo,{"Column1", "Data"}),
				 
				    //Criação de Colunas Adicionais
				    //Criar Coluna ANO
				    Ano = Table.AddColumn(RenomeiaColuna, "Ano", each Date.Year([Data]),Int64.Type),
				    //Criar Coluna Mês
				    Mes = Table.AddColumn(Ano, "Mes", each Date.Month([Data]),Int64.Type),
				    //Criar Coluna Nome do Mês
				    Nome_Mes = Table.AddColumn(Mes, "Nome_Mes", each Date.MonthName([Data]), type text),
				    //Criar Coluna Dia
				    Dia_do_Mes = Table.AddColumn(Nome_Mes, "Dia_Mes", each Date.Day([Data]), Int64.Type),
				    //Criar Coluna Dia do Ano
				    Dia_do_Ano = Table.AddColumn(Dia_do_Mes, "Dia_Ano", each Date.DayOfYear([Data]), Int64.Type),
				    //Criar Coluna Dia da Semana
				    Dia_Semana = Table.AddColumn(Dia_do_Ano, "Dia_Semana", each Date.DayOfWeek([Data]), Int64.Type),
				    //Criar Coluna Dia da Semana
				    Nome_Dia_Semana = Table.AddColumn(Dia_Semana, "Nome_Dia_Semana", each Date.DayOfWeekName([Data]), type text),
				    //Criar Coluna Dia da Semana
				    Trimestre = Table.AddColumn(Nome_Dia_Semana, "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
				    //Criar Coluna Semana do Ano
				    Semana_Ano = Table.AddColumn(Trimestre, "Semana_Ano", each Date.WeekOfYear([Data]), Int64.Type),
				    //Criar Coluna Semana do Mes
				    Semana_Mes = Table.AddColumn(Semana_Ano, "Semana_Mes", each Date.WeekOfMonth([Data]), Int64.Type),
				    #"Colocar Cada Palavra Em Maiúscula" = Table.TransformColumns(Semana_Mes,{{"Nome_Mes", Text.Proper, type text}}),
				    #"Primeiros Caracteres Inseridos" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula", "Primeiros caracteres", each Text.Start([Nome_Mes], 3), type text),
				    #"Colocar Cada Palavra Em Maiúscula1" = Table.TransformColumns(#"Primeiros Caracteres Inseridos",{{"Nome_Dia_Semana", Text.Proper, type text}}),
				    #"Primeiros Caracteres Inseridos1" = Table.AddColumn(#"Colocar Cada Palavra Em Maiúscula1", "Primeiros caracteres.1", each Text.Start([Nome_Dia_Semana], 3), type text)
				
				in
				    #"Primeiros Caracteres Inseridos1"
				```

	annotation PBI_ResultType = Table

