table 'Cliente Final'
	lineageTag: 56bb4695-2262-40d0-bd1f-46df83a36be2

	column Descricao_ClienteFinal
		dataType: string
		lineageTag: 2643213e-460e-4b4f-9cfc-11e6e2d8c79b
		summarizeBy: none
		sourceColumn: Descricao_ClienteFinal

		annotation SummarizationSetBy = Automatic

	column Cod_ClienteFinal
		dataType: int64
		formatString: 0
		lineageTag: 64076b70-05bb-4b65-bcd1-39be74c10fd6
		summarizeBy: none
		sourceColumn: Cod_ClienteFinal

		annotation SummarizationSetBy = Automatic

	partition 'Cliente Final' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://sesigoias-my.sharepoint.com/personal/observatorio_iel_fieg_com_br/Documents/Painel%20Gest%C3%A3o%20De%20Projetos/Base%20De%20Dados/Gest%C3%A3o%20de%20Projetos%20-modelo%202%20-%20Planilha%20de%20acompanhamento%20-%20observat%C3%B3rio.xlsx"), null, true),
				    #"Cliente Final_Sheet" = Fonte{[Item="Cliente Final",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cliente Final_Sheet",{{"Column1", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Descricao_ClienteFinal"}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Colunas Renomeadas", "Índice", 0, 1, Int64.Type),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Índice Adicionado",{{"Índice", "Cod_ClienteFinal"}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Colunas Renomeadas1",1),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Superiores Removidas", each ([Descricao_ClienteFinal] <> null))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

