table 'Etapas Macro'
	lineageTag: e470d850-3470-4a5d-910c-af838f1da257

	column Descricao_EtapasMacro
		dataType: string
		lineageTag: 2f6ba27c-dacc-425e-9b03-7e060406c857
		summarizeBy: none
		sourceColumn: Descricao_EtapasMacro

		annotation SummarizationSetBy = Automatic

	column Cod_EtapasMacro
		dataType: int64
		formatString: 0
		lineageTag: 48e2246d-e557-4218-945a-399787dd0338
		summarizeBy: none
		sourceColumn: Cod_EtapasMacro

		annotation SummarizationSetBy = Automatic

	partition 'Etapas Macro' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://sesigoias-my.sharepoint.com/personal/observatorio_iel_fieg_com_br/Documents/Painel%20Gest%C3%A3o%20De%20Projetos/Base%20De%20Dados/Gest%C3%A3o%20de%20Projetos%20-modelo%202%20-%20Planilha%20de%20acompanhamento%20-%20observat%C3%B3rio.xlsx"), null, true),
				    #"Etapas Macro_Sheet" = Fonte{[Item="Etapas Macro",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Etapas Macro_Sheet",{{"Column1", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Descricao_EtapasMacro"}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Colunas Renomeadas", "Índice", 0, 1, Int64.Type),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Índice Adicionado",{{"Índice", "Cod_EtapasMacro"}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Colunas Renomeadas1",1)
				in
				    #"Linhas Superiores Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

