table Medidas
	lineageTag: b4d0a7b4-9847-4cc6-84f3-b08477752b85

	measure 'Custo Total Previsto' = ```
			SUM(BaseCusto[Custo Total Previsto ]) 
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 41122ed5-625f-451d-b631-f6934479c814

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Desc_Cliente = If([Horas Realizadas] > 0,  MAX(BaseProjetos[Cliente]))
		lineageTag: 4a047a63-2b59-4d56-8333-65d13ce515f0

	measure 'Horas Previstas' = SUM(BaseCusto[Horas Previstas])
		formatString: 0.00
		lineageTag: 36b34e47-1671-4f6c-aa73-a57d2f7080b1

	measure 'Horas Realizadas' = SUM(BaseAtividades[Horas Realizadas])
		lineageTag: f3ac762f-78b7-44b7-bd98-243c9be901f2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Custo Total Realizado' =
			
			SUMX(
			    BaseAtividades,
			    BaseAtividades[Horas Realizadas] * RELATED('Auxiliar 1 - Responsável'[Valor da Hora])
			)
		lineageTag: f6f39156-055c-4b05-8894-c780272d60db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Diferença Valor Projeto' = [Custo Total Realizado] - [Custo Total Previsto]
		lineageTag: 6625617e-2820-4da1-9266-83194c6d2ae6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Diferença horas Projeto' = [Horas Realizadas] - [Horas Previstas]
		lineageTag: c0390125-cbe9-4dea-aaed-5b6bf973a380

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Nome Integrante (Somente quando há horas)' =
			
			IF(
			    ISINSCOPE('Auxiliar 1 - Responsável'[Nome do Integrante]) &&
			    NOT ISBLANK([Horas Previstas]) &&
			    NOT ISBLANK([Horas Realizadas]),
			    SELECTEDVALUE('Auxiliar 1 - Responsável'[Nome do Integrante]),
			    BLANK()
			)
		lineageTag: de03cd17-b042-4b1b-9b84-a54d5641bbcc

	partition Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

