table Medidas
	lineageTag: e427e664-d71e-4e0a-a132-70f88fc3ab40

	measure 'Qtd Projeto' =
			var valor =  CALCULATE( COUNTROWS('Projetos Observatorio'), 'Projetos Observatorio'[Total de Horas] > 0,USERELATIONSHIP('Projetos Observatorio'[Data Término do Projeto],Calendario[Data]),USERELATIONSHIP('Status do Projeto'[Cod_Status],'Projetos Observatorio'[Cod_Status]))
			RETURN
			IF(valor = BLANK(),0,valor)
		formatString: 0
		displayFolder: Medidas_Gerais
		lineageTag: b15fe53c-a8c7-40e7-ad4a-2c670b0278ba

	measure 'Qtd Atividades' = ```
			
			VAR valor = CALCULATE(COUNT('Atividades Observatorio'[Tarefa]))
			RETURN
			IF(valor = BLANK(), 0, valor)
			
			```
		formatString: #,0
		displayFolder: Medidas_Gerais
		lineageTag: 03478c2f-3959-4186-a512-c38dfd5d5691

	measure 'Total horas Atividades' = ```
			
			  VAR TotalHoras = SUM('Atividades Observatorio'[Horas Utilizadas])
			  VAR TotalHorasEmHoras = TotalHoras * 24
			  VAR Horas = INT(TotalHorasEmHoras)
			  VAR Minutos = ROUND((TotalHorasEmHoras - Horas) * 60, 0)
			  RETURN
			    IF(
			      ISBLANK(TotalHoras) || TotalHoras = 0,
			      BLANK(),
			      FORMAT(Horas, "#,00") & ":" & FORMAT(Minutos, "00")
			    )
			
			 
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 40713018-fa98-4c9b-b549-e8660caca076

	measure HorasEstimadas =
			VAR UltimaData = CALCULATE(LASTDATE('Projetos Observatorio'[Data Término do Projeto]), ALLSELECTED('Projetos Observatorio'[Data Término do Projeto]))
			VAR TotalHoras = CALCULATE(SUM('Subetapas do projeto'[Horas Estimadas]), Calendario[Data] = UltimaData)
			RETURN
			TotalHoras
		formatString: #,0
		displayFolder: Medidas_Gerais
		lineageTag: d67a88fb-7f2c-4b37-a364-beb90681f6ac

	measure DiferencaHorasDecimal = ```
			
			    VAR TotalHorasProduzidas = [Total horas Atividades Decimal]
			    VAR TotalHorasEstimadas = [HorasEstimadas]
			    VAR DiferencaHoras =TotalHorasProduzidas - TotalHorasEstimadas 
			    var if2 = IF(TotalHorasEstimadas = BLANK(),BLANK(),DiferencaHoras)
			   
			   RETURN
			  if2
			```
		displayFolder: Medidas_Gerais
		lineageTag: 8b928121-eb33-4bac-ae73-861253f0f6c2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'horas estimada / horas realizadas' = ```
			
			
			    VAR TotalHorasProduzidas = SUM('Atividades Observatorio'[Horas Utilizadas]) *24
			    VAR TotalHorasEstimadas = [HorasEstimadas]
			    VAR DiferencaHoras =DIVIDE(TotalHorasProduzidas,TotalHorasEstimadas)
			        RETURN
			        IF(
			            ISBLANK(DiferencaHoras) || DiferencaHoras = 0,
			            BLANK(),
			            DiferencaHoras
			        )
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Medidas_Gerais
		lineageTag: 52b6b2d3-1161-44a1-800e-44bde8daf0f2

	measure HorasEstimadasFormatada = ```
			
			VAR UltimaData = CALCULATE(LASTDATE('Projetos Observatorio'[Data Término do Projeto]), ALLSELECTED('Projetos Observatorio'[Data Término do Projeto]))
			VAR TotalHoras = CALCULATE([HorasEstimadas], Calendario[Data] = UltimaData,USERELATIONSHIP('Projetos Observatorio'[Cod_Status],'Status do Projeto'[Cod_Status]))
			    
			    VAR Horas = INT(TotalHoras)
			    VAR Minutos = ROUND((TotalHoras - Horas) * 60, 0)
			    RETURN
			        IF(
			            ISBLANK(TotalHoras) || TotalHoras = 0,
			            BLANK(),
			            FORMAT(Horas, "##,00") & ":" & FORMAT(Minutos, "00")
			        )
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 290b8566-f3c4-4dc6-84eb-e977b80ee1f2

	measure ValorGasto = ```
			
			
			var div = SUMX(
			    'Atividades Observatorio',
			    [valorHoraindividual] * [Total horas Atividades Decimal]
			)
			RETURN
			IF(div = 0,BLANK(),div)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Medidas_Gerais
		lineageTag: 141b15d5-ad2d-4e86-84e6-f9cb2173c5a9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure valorHoraindividual = ```
			SUM('Tabela Hora x Custo Colaborador'[Valor Hora (R$)]) 
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Medidas_Gerais
		lineageTag: 4a869e07-78a5-4c12-93f7-32b654f3ed70

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure HorasDecimais = ```
			
			SUMX(
			    ADDCOLUMNS(
			        'Atividades Observatorio',
			        "HorasMinutos",
			       TIME(
			        VALUE(LEFT([Total horas Atividades], FIND(":", [Total horas Atividades]) - 1)), 
			        VALUE(MID([Total horas Atividades], FIND(":", [Total horas Atividades]) + 1, 2)), 
			        0
			    )
			    ),
			    HOUR([HorasMinutos]) + MINUTE([HorasMinutos]) / 60
			)
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 3b27e083-2913-4deb-a402-c68e37b498d4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total horas Atividades Decimal' = ```
			
			 var valor = CALCULATE(SUM('Atividades Observatorio'[Horas Utilizadas])) * 24
			RETURN
			IF(valor = BLANK(),0,valor)
			
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 80b16a49-9368-487a-aeef-c9eda3249a0a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HorasEstimadasTarget =
			
			var valor =  [HorasEstimadas]*1.5
			RETURN
			IF(valor = BLANK(),0,valor)
		formatString: #,0
		displayFolder: Medidas_Gerais
		lineageTag: ab3b07d1-cce7-4d67-954a-5cc495ff9673

		annotation PBI_FormatHint = {"isDecimal":true}

	measure CorGaugehoras = ```
			
			 SWITCH(
			    TRUE(),
			    [Total horas Atividades Decimal] < [HorasEstimadas],"#23325F",
			    [Total horas Atividades Decimal] = [HorasEstimadas],"#FAB900",
			    [Total horas Atividades Decimal] > [HorasEstimadas], "#19AA5F"
			 )
			```
		displayFolder: Medidas_Gerais
		lineageTag: 3e8acafb-b1ae-453c-85c9-ab67ea7556b2

	measure DiferencaHorasFormatada = ```
			
			    VAR DiferencaHoras = [DiferencaHorasDecimal]
			    VAR TotalHoras = INT(ABS(DiferencaHoras))
			    VAR TotalMinutos = ROUND((ABS(DiferencaHoras) - TotalHoras) * 60, 0)
			    VAR Sign = IF(DiferencaHoras < 0, "-", "")
			    VAR Horas = TotalHoras + INT(TotalMinutos / 60)
			    VAR Minutos = MOD(TotalMinutos, 60)
			    VAR FormattedHours = FORMAT(Horas, "#,0")
			    VAR FormattedMinutes = FORMAT(Minutos, "00")
			    var horasest = [HorasEstimadas]
			    RETURN
			        IF(
			            ISBLANK(DiferencaHoras) || horasest = BLANK(),
			            BLANK(),
			            IF(
			                DiferencaHoras < 0 && Horas = 0 && Minutos = 0,
			                "0:00",
			                Sign & FormattedHours & ":" & FormattedMinutes
			            )
			        )
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: fbdf5967-4b0d-4e73-9d9c-356fc349e5f9

	measure valorEstimado =
			
			VAR UltimaData = CALCULATE(LASTDATE('Projetos Observatorio'[Data Término do Projeto]), ALLSELECTED('Projetos Observatorio'[Data Término do Projeto]))
			VAR valor = CALCULATE(
			    SUM('Projetos Observatorio'[Total do Projeto (R$)]),
			    USERELATIONSHIP(Calendario[Data], 'Projetos Observatorio'[Data Término do Projeto]),
			    Calendario[Data] = UltimaData, USERELATIONSHIP('Status do Projeto'[Cod_Status],'Projetos Observatorio'[Cod_Status])
			)
			RETURN
			    IF(valor = BLANK(), 0, valor)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		displayFolder: Medidas_Gerais
		lineageTag: 98fa86ff-4cb0-4d28-99a2-1e9e1f628a39

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure valorEstimadoTarget = ```
			
			 var valor = SUM('Projetos Observatorio'[Total do Projeto (R$)])*1.25
			 RETURN
			 IF(valor = BLANK(),0,valor)
			```
		formatString: #,0.00
		displayFolder: Medidas_Gerais
		lineageTag: 094d5af3-7382-468c-861c-35d976e479ed

	measure CorGaugevalor = ```
			
			 SWITCH(
			    TRUE(),
			    [ValorGasto] < [valorEstimado],"#23325F",
			    [ValorGasto] = [valorEstimado],"#FAB900",
			    [ValorGasto] > [valorEstimado], "#19AA5F"
			 )
			```
		displayFolder: Medidas_Gerais
		lineageTag: af324884-f460-4bb3-a93d-8b6f01edf7ad

	measure 'Total horas Atividades 0' = ```
			
			  VAR TotalHoras = SUM('Atividades Observatorio'[Horas Utilizadas])
			  VAR TotalHorasEmHoras = TotalHoras * 24
			  VAR Horas = INT(TotalHorasEmHoras)
			  VAR Minutos = ROUND((TotalHorasEmHoras - Horas) * 60, 0)
			  RETURN
			    IF(
			      ISBLANK(TotalHoras) || TotalHoras = 0,
			      0,
			      FORMAT(Horas, "##,00") & ":" & FORMAT(Minutos, "00" )
			    )
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 83bbd23d-0602-4098-9ee9-5a4d8161a2dc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'ValorGasto 0' = ```
			
			var teste = SUMX(
			    'Atividades Observatorio',
			    [valorHoraindividual] * [Total horas Atividades Decimal])
			RETURN
			IF(ISBLANK(teste), 0, teste)
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Medidas_Gerais
		lineageTag: 24a81ffb-68a3-46f6-9766-531fd586a6c3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure TotalHorasEmMinutos =
			
			VAR TotalHoras = SUM('Atividades Observatorio'[Horas Utilizadas])
			RETURN TotalHoras * 24 * 60
		displayFolder: Medidas_Gerais
		lineageTag: feaae412-30b3-4696-8d60-75c6315a7453

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure TotalHorasClassificavel = ```
			
			VAR TotalHoras = SUM('Atividades Observatorio'[Horas Utilizadas])
			VAR TotalHorasEmHoras = TotalHoras * 24
			VAR Horas = INT(TotalHorasEmHoras)
			VAR Minutos = ROUND((TotalHorasEmHoras - Horas) * 60, 0)
			VAR Classificacao = TotalHoras * 24 * 60 -- tempo total em minutos para classificação
			RETURN
			    IF(
			        ISBLANK(TotalHoras) || TotalHoras = 0,
			        BLANK(),
			        Classificacao & " - " & FORMAT(Horas, "00") & ":" & FORMAT(Minutos, "00")
			    )
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: d8d3f4bd-ecc2-404a-a703-5e1c509c6901

	measure 'Qtd Atividades Em Andamento' = ```
			
			VAR valor = CALCULATE(COUNT('Atividades Observatorio'[Tarefa]),'Status do Projeto'[Cod_Status] = 2,USERELATIONSHIP('Status do Projeto'[Cod_Status],'Atividades Observatorio'[Cod_Status]))
			RETURN
			IF(valor = BLANK(), 0, valor)
			
			```
		formatString: 0
		displayFolder: Medidas_Gerais
		lineageTag: 77cd944a-73a4-4e0b-afa3-e741e939d26f

	measure 'Qtd Projeto em andamentos' =
			var valor =  CALCULATE( COUNTROWS('Projetos Observatorio'), 'Projetos Observatorio'[Total de Horas] > 0, 'Status do Projeto'[Cod_Status] =2)
			RETURN
			IF(valor = BLANK(),0,valor)
		formatString: 0
		displayFolder: Medidas_Gerais
		lineageTag: 79428156-8194-435e-90a5-f2e37640e776

	measure 'Dias Trabalhados' = ```
			
			VAR horas = 
			[Total horas Atividades Decimal]
			VAR cargahoraria = 
			    SUM('Tabela Hora x Custo Colaborador'[Carga horário diária])
			RETURN
			    IF(
			        ISBLANK(cargahoraria) || cargahoraria = 0,
			        BLANK(),
			        horas / cargahoraria
			    )
			
			```
		formatString: #,0
		displayFolder: Medidas_Gerais
		lineageTag: 2deba70a-47e8-4c47-b632-fc5f030a341a

	measure 'Qtd Atividades blank' = ```
			
			VAR valor =  CALCULATE(COUNT('Atividades Observatorio'[Tarefa]))
			RETURN
			if(valor = 0 ,BLANK(),valor)
			
			```
		formatString: 0
		displayFolder: Medidas_Gerais
		lineageTag: 25a45d65-3fe3-44be-9433-7656fa902170

	measure 'Total horas Atividades Decimal blank' = ```
			
			 var valor = SUM('Atividades Observatorio'[Horas Utilizadas]) * 24
			RETURN
			valor
			
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 79bcbd8f-2c7d-448a-bc4f-05d5755da43e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total horas Atividades Card' = ```
			
			  VAR TotalHoras = SUM('Atividades Observatorio'[Horas Utilizadas])
			  VAR TotalHorasEmHoras = TotalHoras * 24
			  VAR Horas = INT(TotalHorasEmHoras)
			  VAR Minutos = ROUND((TotalHorasEmHoras - Horas) * 60, 0)
			  RETURN
			    IF(
			      ISBLANK(TotalHoras) || TotalHoras = 0,
			      BLANK(),
			       FORMAT(Horas, "##,00") & ":" & FORMAT(Minutos, "00")
			    )
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 38311908-736d-4fb9-bc52-4b5565de9f0a

	measure ValorGasto2 =
			
			var div = [valorHoraindividual]*[Total horas Atividades Decimal]
			RETURN
			IF(div = 0,BLANK(),div)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		displayFolder: Medidas_Gerais
		lineageTag: 41e94f7c-099a-4bd6-9cc0-d606d672dff3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure DiasPassados = ```
			
			VAR DataInicio = SELECTEDVALUE('Projetos Observatorio'[Data Início do Projeto])
			VAR DataFim = IF(
			    SELECTEDVALUE('Atividades Observatorio'[Cod_Status]) = 4, 
			    SELECTEDVALUE('Projetos Observatorio'[Data Término do Projeto]), 
			    TODAY()
			)
			RETURN DATEDIFF(DataInicio, DataFim, DAY)
			
			```
		formatString: 0
		displayFolder: Medidas_Desvio
		lineageTag: d8b1c180-0ece-45bc-80dc-cd3f886dd027

	measure TaxaProgressoDiario = ```
			
			VAR HorasGastas = [Total horas Atividades Decimal]
			VAR DiasPassados = [DiasPassados]
			VAR Divisao = DIVIDE(HorasGastas, DiasPassados, BLANK())
			RETURN 
			Divisao
			```
		displayFolder: Medidas_Desvio
		lineageTag: 768f199e-66c3-43d7-a98d-8f154ed75025

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure DiasRestantesEstimados = ```
			
			VAR HorasEstimadas = [HorasEstimadas]
			VAR HorasGastas = [Total horas Atividades Decimal]
			Var Sub =  HorasEstimadas - HorasGastas
			VAR TaxaProgressoDiario = [TaxaProgressoDiario]
			RETURN 
			 IF(
			    SELECTEDVALUE('Status do Projeto'[Cod_Status]) = 4, 
			    BLANK(), 
			    DIVIDE(HorasEstimadas - HorasGastas, TaxaProgressoDiario, BLANK())
			)
			```
		displayFolder: Medidas_Desvio
		lineageTag: d7e0dec1-9d61-49b4-aebf-75fdfb171e67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure HorasEstimadasDecimal = ```
			
			 var soma = CALCULATE(SUM('Subetapas do projeto'[Horas Estimadas]),USERELATIONSHIP('Projetos Observatorio'[Data Término do Projeto],Calendario[Data]))
			 RETURN
			 soma*24
			```
		formatString: 0
		displayFolder: Medidas_Gerais
		lineageTag: 6733ee6c-1c04-4595-8fa5-6d4b65ddabe7

	measure PrevisaoTermino = ```
			
			VAR DiasRestantes = [DiasRestantesEstimados]
			VAR hoje = TODAY()
			RETURN 
			SWITCH(
			    TRUE(),
			    SELECTEDVALUE('Status do Projeto'[Cod_Status]) = 4, SELECTEDVALUE('Projetos Observatorio'[Data Término do Projeto]),
			    hoje + DiasRestantes
			)
			```
		formatString: General Date
		displayFolder: Medidas_Desvio
		lineageTag: 20f6fdaf-7e7e-4e34-b351-b093eafdc2b4

	measure DiasPlanejados =
			
			DATEDIFF(
			    SELECTEDVALUE('Projetos Observatorio'[Data Início do Projeto]),
			    SELECTEDVALUE('Projetos Observatorio'[Data Término do Projeto]),DAY)
		formatString: 0
		displayFolder: Medidas_Desvio
		lineageTag: 34e175fd-4031-4a68-a1c0-fa1b1b7a99ee

	measure 'Desvio de Custo %' = ```
			
			var CustoEfetivo = [ValorGasto]
			var ValorPlanejado = CALCULATE(SUM('Projetos Observatorio'[Total do Projeto (R$)]),USERELATIONSHIP('Projetos Observatorio'[Data Término do Projeto],Calendario[Data]))
			var sub =  CustoEfetivo - ValorPlanejado
			var div = DIVIDE(sub,ValorPlanejado)
			RETURN
			If(div = -1,BLANK(),div)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: d95e8b09-8ee6-45d4-b30c-52f42ccf2e43

	measure 'Desvio de Custo Valor' = ```
			
			var CustoEfetivo = [ValorGasto]
			var ValorPlanejado = SUM('Projetos Observatorio'[Total do Projeto (R$)])
			var sub =  CustoEfetivo - ValorPlanejado
			RETURN
			sub
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 00e6d06e-5b6e-41a1-89e3-02b4198c0a33

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'desvio de Esforço' = DIVIDE([Total horas Atividades Decimal],[HorasEstimadas])
		formatString: 0%;-0%;0%
		lineageTag: 253261df-4fd0-4d8f-8f08-834965193d04

	measure CorGrafBarrasEsforço = ```
			
			 SWITCH(
			    TRUE(),
			    [desvio de Esforço] <= 0.3,"#23325F",
			    [desvio de Esforço] <= 0.6,"#FAB900",
			    [desvio de Esforço] >0.6,"#19AA5F"
			 )
			```
		displayFolder: Medidas_Gerais
		lineageTag: c0d3e5e5-c03d-4d12-8d17-45d05d42a185

	measure RankColaboradores = ```
			
			 RANKX(
			    ALLSELECTED('Tabela Hora x Custo Colaborador'[Colaboradores]),
			    [Total horas Atividades Decimal]
			 )
			```
		formatString: 0
		displayFolder: Medidas_Gerais\Ranking
		lineageTag: 80ff9e55-b39e-4000-87a9-6d68b2ec23f5

	measure 'Top 3 Nome' = ```
			
			CALCULATE(
			    SELECTEDVALUE('Tabela Hora x Custo Colaborador'[Colaboradores]),
			    FILTER(
			        VALUES('Tabela Hora x Custo Colaborador'[Colaboradores]),
			        [RankColaboradores] = 3
			    )
			 )
			
			```
		displayFolder: Medidas_Gerais\Ranking
		lineageTag: 543f8146-27e4-41bc-a610-2fe8ca6bd22f

	measure 'Top 2 Nome' = ```
			
			 CALCULATE(
			    SELECTEDVALUE('Tabela Hora x Custo Colaborador'[Colaboradores]),
			    FILTER(
			        VALUES('Tabela Hora x Custo Colaborador'[Colaboradores]),
			        [RankColaboradores] = 2
			    )
			 )
			```
		displayFolder: Medidas_Gerais\Ranking
		lineageTag: 29a70949-30d3-4b50-8c82-3a04d5c8ca2e

	measure 'Top 1 Nome' = ```
			
			 CALCULATE(
			    SELECTEDVALUE('Tabela Hora x Custo Colaborador'[Colaboradores]),
			    FILTER(
			        VALUES('Tabela Hora x Custo Colaborador'[Colaboradores]),
			        [RankColaboradores] = 1
			    )
			 )
			```
		displayFolder: Medidas_Gerais\Ranking
		lineageTag: 9c3074cc-02ea-4c7f-998d-6b5d23cabb72

	measure 'Top 1 Horas' = ```
			
			 var calc = CALCULATE(
			    [Total horas Atividades],
			    FILTER(
			        VALUES('Tabela Hora x Custo Colaborador'[Colaboradores]),
			        [RankColaboradores] = 1
			    )
			 )
			 RETURN
			calc & " Horas"
			```
		displayFolder: Medidas_Gerais\Ranking
		lineageTag: 3e518076-d96f-47cd-8fb1-6b230067e153

	measure 'Top 2 Horas' = ```
			
			 var calc = CALCULATE(
			    [Total horas Atividades],
			    FILTER(
			        VALUES('Tabela Hora x Custo Colaborador'[Colaboradores]),
			        [RankColaboradores] = 2
			    )
			 )
			 RETURN
			calc & " Horas"
			```
		displayFolder: Medidas_Gerais\Ranking
		lineageTag: 1ab1a90c-1ef2-4f7a-9923-dcd8c7d818cf

	measure 'Top 3 Horas' = ```
			
			 var calc = CALCULATE(
			    [Total horas Atividades],
			    FILTER(
			        VALUES('Tabela Hora x Custo Colaborador'[Colaboradores]),
			        [RankColaboradores] = 3
			    )
			 )
			 RETURN
			calc & " Horas"
			```
		displayFolder: Medidas_Gerais\Ranking
		lineageTag: 878dddfe-1147-4429-a906-8b7c5c1a97b5

	measure 'HorasEstimadasFormatada 0' = ```
			
			VAR UltimaData = CALCULATE(LASTDATE('Projetos Observatorio'[Data Término do Projeto]), ALLSELECTED('Projetos Observatorio'[Data Término do Projeto]))
			VAR TotalHoras = CALCULATE([HorasEstimadas], Calendario[Data] = UltimaData,USERELATIONSHIP('Projetos Observatorio'[Cod_Status],'Status do Projeto'[Cod_Status]))
			    
			    VAR Horas = INT(TotalHoras)
			    VAR Minutos = ROUND((TotalHoras - Horas) * 60, 0)
			    RETURN
			        IF(
			            ISBLANK(TotalHoras) || TotalHoras = 0,
			            0,
			            FORMAT(Horas, "##,00") & ":" & FORMAT(Minutos, "00")
			        )
			
			```
		displayFolder: Medidas_Gerais
		lineageTag: 3cca8534-4558-4751-a212-812011365476

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

