table 'Status do Projeto'
	lineageTag: 29420b16-ff35-4d9b-a2bc-a6b99336b3d1

	column Descricao_status
		dataType: string
		lineageTag: af58bb56-0bd7-4957-884c-c1278c8e39b0
		summarizeBy: none
		sourceColumn: Descricao_status

		annotation SummarizationSetBy = Automatic

	column Cod_Status
		dataType: int64
		formatString: 0
		lineageTag: 14f79acf-26e8-4851-b4e5-8715e2ab4b44
		summarizeBy: none
		sourceColumn: Cod_Status

		annotation SummarizationSetBy = Automatic

	partition 'Status do Projeto' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://sesigoias-my.sharepoint.com/personal/observatorio_iel_fieg_com_br/Documents/Painel%20Gest%C3%A3o%20De%20Projetos/Base%20De%20Dados/Gest%C3%A3o%20de%20Projetos%20-modelo%202%20-%20Planilha%20de%20acompanhamento%20-%20observat%C3%B3rio.xlsx"), null, true),
				    #"Status do Projeto_Sheet" = Fonte{[Item="Status do Projeto",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Status do Projeto_Sheet",{{"Column1", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Descricao_status"}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Colunas Renomeadas", "Índice", 0, 1, Int64.Type),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Índice Adicionado",{{"Índice", "Cod_Status"}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Colunas Renomeadas1",1)
				in
				    #"Linhas Superiores Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

