table 'Tabela Hora x Custo Colaborador'
	lineageTag: 5d6d866d-b2d4-437f-98fe-436be69adc8e

	column COD
		dataType: int64
		formatString: 0
		lineageTag: 2f6db8ae-a1bb-46da-a635-8593e916b818
		summarizeBy: none
		sourceColumn: COD

		annotation SummarizationSetBy = Automatic

	column Colaboradores
		dataType: string
		lineageTag: 7065f4f6-e39c-42c3-ab46-3946d1608162
		summarizeBy: none
		sourceColumn: Colaboradores

		annotation SummarizationSetBy = Automatic

	column Função
		dataType: string
		lineageTag: c0d859fd-7e6c-4174-9166-87e23dbc65b9
		summarizeBy: none
		sourceColumn: Função

		annotation SummarizationSetBy = Automatic

	column 'Carga horário diária'
		dataType: int64
		formatString: 0
		lineageTag: 7c557fa6-b705-4287-8452-680a637a89d9
		summarizeBy: none
		sourceColumn: Carga horário diária

		annotation SummarizationSetBy = Automatic

	column 'Carga horário Mensal'
		dataType: int64
		formatString: 0
		lineageTag: fa40d963-3680-4a55-a435-2c1e1c9a81df
		summarizeBy: none
		sourceColumn: Carga horário Mensal

		annotation SummarizationSetBy = Automatic

	column 'Valor Hora (R$)'
		dataType: decimal
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: f96889aa-00e8-4e02-b299-ab428821a5fb
		summarizeBy: sum
		sourceColumn: Valor Hora (R$)

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Column8
		dataType: string
		lineageTag: c8e1d459-36f5-40f5-8b31-ab75d372406e
		summarizeBy: none
		sourceColumn: Column8

		annotation SummarizationSetBy = Automatic

	column 'Modelo de Contrato'
		dataType: string
		lineageTag: 931774ae-e4a5-4434-bdcc-fb0af0ee3ede
		summarizeBy: none
		sourceColumn: Modelo de Contrato

		annotation SummarizationSetBy = Automatic

	column Column9
		dataType: string
		lineageTag: cb22d03f-3b98-4143-b8ae-e5745178b892
		summarizeBy: none
		sourceColumn: Column9

		annotation SummarizationSetBy = Automatic

	partition 'Tabela Hora x Custo Colaborador' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://sesigoias-my.sharepoint.com/personal/observatorio_iel_fieg_com_br/Documents/Painel%20Gest%C3%A3o%20De%20Projetos/Base%20De%20Dados/Gest%C3%A3o%20de%20Projetos%20-modelo%202%20-%20Planilha%20de%20acompanhamento%20-%20observat%C3%B3rio.xlsx"), null, true),
				    #"Tabela Hora x Custo Colaborador_Sheet" = Fonte{[Item="Tabela Hora x Custo Colaborador",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tabela Hora x Custo Colaborador_Sheet", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"COD", Int64.Type}, {"Colaboradores", type text}, {"Função", type text}, {"Carga horário diária", Int64.Type}, {"Carga horário Mensal", Int64.Type}, {"Valor Hora (R$)", Currency.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

