table 'Áreas da Demanda'
	lineageTag: 9618c07b-c22b-4f45-b9ee-58917196b2a1

	column Descricao_Demanda
		dataType: string
		lineageTag: 40508f09-c76b-4244-b365-334f1e1482c3
		summarizeBy: none
		sourceColumn: Descricao_Demanda

		annotation SummarizationSetBy = Automatic

	column Cod_Demanda
		dataType: int64
		formatString: 0
		lineageTag: 2858556a-f6e6-40d3-9fbe-e6377fbde976
		summarizeBy: none
		sourceColumn: Cod_Demanda

		annotation SummarizationSetBy = Automatic

	partition 'Áreas da Demanda' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://sesigoias-my.sharepoint.com/personal/observatorio_iel_fieg_com_br/Documents/Painel%20Gest%C3%A3o%20De%20Projetos/Base%20De%20Dados/Gest%C3%A3o%20de%20Projetos%20-modelo%202%20-%20Planilha%20de%20acompanhamento%20-%20observat%C3%B3rio.xlsx"), null, true),
				    #"Áreas da Demanda_Sheet" = Fonte{[Item="Áreas da Demanda",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Áreas da Demanda_Sheet",{{"Column1", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Column1", "Descricao"}}),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Colunas Renomeadas", "Índice", 0, 1, Int64.Type),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Índice Adicionado",{{"Índice", "Cod_Demanda"}, {"Descricao", "Descricao_Demanda"}}),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Colunas Renomeadas1",1),
				    #"Linhas Filtradas" = Table.SelectRows(#"Linhas Superiores Removidas", each ([Descricao_Demanda] <> null and [Descricao_Demanda] <> "0")),
				    #"Duplicatas Removidas" = Table.Distinct(#"Linhas Filtradas"),
				    #"Duplicatas Removidas1" = Table.Distinct(#"Duplicatas Removidas", {"Descricao_Demanda"})
				in
				    #"Duplicatas Removidas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

